### ISSUE TITLE
How do I start ORB-SLAM3 with ASL format data

### ISSUE THREAD

**Issue by liangchen97** [hellovuong/Associate_datasets#1]
@hellovuong 
Hello!Thanks for your help and clear explanation, now I can get the image folder and imu. txt, but since I used the ROS method to start ORB-SLAM3 before, I still have some problems about how to start ASL Format. I tried to use a command similar to the following but it didn't work.What is the input here?
/Monocular-Inertial/mono_inertial_euroc ../Vocabulary/ORBvoc.txt ./Monocular-Inertial/EuRoC.yaml "$pathDatasetEuroc"/V102 ./Monocular-Inertial/EuRoC_TimeStamps/V102.txt dataset-V102_monoi

For Mono_inertial_d455.cc file, I tried to compile it using ./build.sh,  but nothing worked. Could I trouble you to explain it?

**Comment by hellovuong** [comment]
You need to compile it first. Open CMakeLists.txt file in ORB_SLAM3 folder and add the following at the end of the file: 
```
add_executable(mono_inertial_d455
Examples/Monocular-Inertial/mono_inertial_d455.cc)
target_link_libraries(mono_inertial_d455 ${PROJECT_NAME})
```
After adding it and build. You can run:
`./mono_inertial_d455 path_to_vocabulary path_to_settings path_to_sequence_folder_1 (path_to_image_folder_2... path_to_image_folder_N dataset_name`

**Comment by liangchen97** [comment]
Okay
Is “path_to_sequence_folder_1” the path to imu.txt?
And what does dateaset_name mean

**Comment by hellovuong** [comment]
`path_to_sequence_folder_1` is the path to your dataset folder. The structure of the folder should be like this:
Folder_1
|
|------------------------ Color: Folder contains images
|------------------------ times_color.txt
|------------------------ imu.txt

`dataset_name` is your dataset name, whatever you want
